### PR TITLE
lowercase d

### PR DESCRIPTION
**Pull request by ChrisSmith**
we rebranded :P

### CODE REVIEW

**Comment by dgant** [comment]
image

**Comment by chris-smith-zocdoc** [comment]
That's.... something

**Comment by mpaulweeks** [comment]
image

**Comment by dgant** [comment]
that's pretty much how i've always felt about the new logo 
image

**Comment by matthew-piziak** [comment]
So glad I subscribed to this thread.

**Comment by matthew-piziak** [comment]
image

**Comment by matthew-piziak** [comment]
image

**Comment by dgant** [comment]
image

**Pull request merged**
